language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.3
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt
  - pip install -e .
script:
  - make test
